initial grafana cloud integration config test

diff --git a/.github/actions/run-pytest-instrumented/action.yml b/.github/actions/run-pytest-instrumented/action.yml
--- a/.github/actions/run-pytest-instrumented/action.yml
+++ b/.github/actions/run-pytest-instrumented/action.yml
@@ -1,5 +1,5 @@
 name: 'Run Pytest Coverage with Configured Instrumentation'
-description: 'Runs pytest with coverage and optional wtrace instrumentation on Windows.'
+description: 'Runs pytest and configured instrumentation (usually coverage, sometimes grafana metrics etc.).'
 inputs:
   pytest_filter_pattern:
     description: 'Pytest filter pattern (optional)'
@@ -26,6 +26,10 @@ inputs:
     description: 'Run CI resource monitor (env value)'
     required: false
     default: ''
+  run_w_grafana:
+    description: 'Run Grafana Alloy resource monitoring (Linux only)'
+    required: false
+    default: '0'
 runs:
   using: 'composite'
   steps:
@@ -64,6 +68,20 @@ runs:
         echo "wtrace_pid=$processId" | Out-File -FilePath $env:GITHUB_ENV -Append
         Start-Sleep -Seconds 2
 
+    - name: Run grafana alloy github/unix prometheus exporter (Linux only)
+      if: runner.os == 'Linux' && inputs.run_w_grafana == '1'
+      uses: ./.github/actions/run-grafana-alloy-exporter
+      with:
+        IT_GRAFANA_GITHUB_TOKEN: ${{ env.IT_GRAFANA_GITHUB_TOKEN }}
+        PROM_PUSH_URL: ${{ env.PROM_PUSH_URL }}
+        GHA_GRAFANA_USER_ID: ${{ env.GHA_GRAFANA_USER_ID }}
+        GHA_ALLOY_WRITE_TOKEN: ${{ env.GHA_ALLOY_WRITE_TOKEN }}
+        GITHUB_RUN_ID: ${{ github.run_id }}
+        GITHUB_WORKFLOW: ${{ github.workflow }}
+        GITHUB_RUN_NUMBER: ${{ github.run_number }}
+        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
+        REPO: speediedan/interpretune
+
     - name: Run tests and coverage
       shell: bash
       continue-on-error: true
@@ -81,6 +99,15 @@ runs:
           PYTEST_CMD="coverage run --append --source src/interpretune -m pytest src/interpretune tests -v --import-mode=importlib --durations=50 --junitxml=junit/test-results-${{ inputs.runner_os }}-py${{ inputs.python_version }}.xml"
         fi
         eval $PYTEST_CMD
+
+        # Check the exit code of the pytest command
+        EXIT_CODE=$?
+        if [ $EXIT_CODE -ne 0 ]; then
+          echo "Pytest failed with exit code $EXIT_CODE."
+          echo "error=true" >> $GITHUB_ENV
+        else
+          echo "error=false" >> $GITHUB_ENV
+        fi
 
     - name: Stop CI resource monitor (Linux only)
       if: runner.os == 'Linux' && inputs.run_resource_monitor == '1'
diff --git a/.github/workflows/ci_test-full.yml b/.github/workflows/ci_test-full.yml
--- a/.github/workflows/ci_test-full.yml
+++ b/.github/workflows/ci_test-full.yml
@@ -26,6 +26,11 @@ on:
         required: false
         default: ''
         type: string
+      run_w_grafana:
+        description: 'Run Grafana Alloy resource monitoring (Linux only)'
+        required: false
+        default: '0'
+        type: string
   push:
     branches: [main, "release/*", "bugfix/*"]
     paths:
@@ -84,24 +89,28 @@ jobs:
       run_resource_monitor: ${{ steps.resolve_dispatch_vars.outputs.run_resource_monitor }}
       enable_os_trace: ${{ steps.resolve_dispatch_vars.outputs.enable_os_trace }}
       pytest_filter_pattern: ${{ steps.resolve_dispatch_vars.outputs.pytest_filter_pattern }}
+      run_w_grafana: ${{ steps.resolve_dispatch_vars.outputs.run_w_grafana }}
     steps:
       - name: Capture manual workflow overrides
         id: capture-manual-overrides
         env:
           # toggle comments here as desired to force more granular logging for this workflow
-          # IT_CI_LOG_LEVEL: ${{ vars.IT_CI_LOG_LEVEL || 'INFO' }}
-          IT_CI_LOG_LEVEL: "DEBUG"
-          # CI_RESOURCE_MONITOR: ${{ vars.CI_RESOURCE_MONITOR || '0' }}
-          CI_RESOURCE_MONITOR: "1"
-          # ENABLE_OS_TRACE: "0"
-          ENABLE_OS_TRACE: "1"
+          IT_CI_LOG_LEVEL: ${{ vars.IT_CI_LOG_LEVEL || 'INFO' }}
+          # IT_CI_LOG_LEVEL: "DEBUG"
+          CI_RESOURCE_MONITOR: ${{ vars.CI_RESOURCE_MONITOR || '0' }}
+          # CI_RESOURCE_MONITOR: "1"
+          ENABLE_OS_TRACE: "0"
+          # ENABLE_OS_TRACE: "1"
           PYTEST_FILTER_PATTERN: ""
-          # PYTEST_FILTER_PATTERN: "test_tl_direct_attr or test_format_columns_all_indices"
+          # PYTEST_FILTER_PATTERN: "test_format_columns_all_indices or test_run_with_saes_with_cache_fwd_bwd"
+          RUN_W_GRAFANA: ${{ vars.RUN_W_GRAFANA || '0' }}
+          # RUN_W_GRAFANA: "1"
         run: |
           echo "IT_CI_LOG_LEVEL=${{ env.IT_CI_LOG_LEVEL || 'INFO' }}" >> $GITHUB_OUTPUT
           echo "CI_RESOURCE_MONITOR=${{ env.CI_RESOURCE_MONITOR || '0' }}" >> $GITHUB_OUTPUT
           echo "ENABLE_OS_TRACE=${{ env.ENABLE_OS_TRACE }}" >> $GITHUB_OUTPUT
           echo "PYTEST_FILTER_PATTERN=${{ env.PYTEST_FILTER_PATTERN }}" >> $GITHUB_OUTPUT
+          echo "RUN_W_GRAFANA=${{ env.RUN_W_GRAFANA || '0' }}" >> $GITHUB_OUTPUT
       - name: Resolve workflow dispatch inputs
         id: resolve_dispatch_vars
         run: |
@@ -109,6 +118,7 @@ jobs:
           echo "run_resource_monitor=${{ inputs.run_resource_monitor != '' && inputs.run_resource_monitor || steps.capture-manual-overrides.outputs.CI_RESOURCE_MONITOR }}" >> $GITHUB_OUTPUT
           echo "enable_os_trace=${{ inputs.enable_os_trace != '' && inputs.enable_os_trace || steps.capture-manual-overrides.outputs.ENABLE_OS_TRACE }}" >> $GITHUB_OUTPUT
           echo "pytest_filter_pattern=${{ inputs.pytest_filter_pattern != '' && inputs.pytest_filter_pattern || steps.capture-manual-overrides.outputs.PYTEST_FILTER_PATTERN }}" >> $GITHUB_OUTPUT
+          echo "run_w_grafana=${{ inputs.run_w_grafana != '' && inputs.run_w_grafana || steps.capture-manual-overrides.outputs.RUN_W_GRAFANA || '1' }}" >> $GITHUB_OUTPUT
   cpu:
     needs: log-dispatch-inputs
     runs-on: ${{ matrix.os }}
@@ -126,6 +136,11 @@ jobs:
       IT_USE_CT_COMMIT_PIN: "1"
       WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
       HF_GATED_PUBLIC_REPO_AUTH_KEY: ${{ secrets.HF_GATED_PUBLIC_REPO_AUTH_KEY }}
+      ### we need to set the below secrets/vars for Grafana Alloy monitoring in our composite action (which doesn't have direct access to those workflow inputs)
+      IT_GRAFANA_GITHUB_TOKEN: ${{ secrets.IT_GRAFANA_GITHUB_TOKEN }}
+      PROM_PUSH_URL: ${{ vars.PROM_PUSH_URL }}
+      GHA_GRAFANA_USER_ID: ${{ secrets.GHA_GRAFANA_USER_ID }}
+      GHA_ALLOY_WRITE_TOKEN: ${{ secrets.GHA_ALLOY_WRITE_TOKEN }}
     steps:
       - uses: actions/checkout@v4
       - name: Set up Python ${{ matrix.python-version }}
@@ -141,7 +156,7 @@ jobs:
       - name: Install libpq (macOS only)
         if: runner.os == 'macOS'
         run: |
-          brew install libpq
+          brew reinstall libpq
           brew link --force libpq
 
       # Note: This uses an internal pip API and may not always work
@@ -180,7 +195,15 @@ jobs:
           workspace: ${{ github.workspace }}
           enable_os_trace: ${{ needs.log-dispatch-inputs.outputs.enable_os_trace }}
           run_resource_monitor: ${{ needs.log-dispatch-inputs.outputs.run_resource_monitor }}
+          run_w_grafana: ${{ needs.log-dispatch-inputs.outputs.run_w_grafana }}
 
+      # we add this step to address edge cases where the pytest step in our composite action will error (which is reported)
+      # but still be marked as "green" in the UI
+      - name: Explicitly raise pytest error status (if present)
+        if: steps.run-pytest-coverage.outputs.error_occurred == 'true'
+        run: |
+          echo "The pytest run exited non-zero, see provided logs."
+          exit 1
 
       - name: Upload pytest results
         uses: actions/upload-artifact@v4
@@ -202,6 +225,29 @@ jobs:
         with:
           name: ci_resource_monitor-log-${{ runner.os }}-${{ matrix.python-version }}
           path: /tmp/ci_resource_monitor.log
+        continue-on-error: true
+
+      - name: Prepare Alloy log (if present)
+        id: prepare-alloy-log
+        if: runner.os == 'Linux' && needs.log-dispatch-inputs.outputs.run_w_grafana == '1'
+        shell: bash
+        run: |
+          if [ -f /tmp/alloy.log ]; then
+            echo "Uploading /tmp/alloy.log as artifact."
+            tar -czf /tmp/alloy-log-${{ runner.os }}-${{ matrix.python-version }}.tar.gz -C /tmp alloy.log
+            echo "file_exists=true" >> $GITHUB_OUTPUT
+          else
+            echo "/tmp/alloy.log not found, skipping upload."
+            echo "file_exists=false" >> $GITHUB_OUTPUT
+          fi
+        continue-on-error: true
+
+      - name: Upload Alloy log artifact
+        if: runner.os == 'Linux' && needs.log-dispatch-inputs.outputs.run_w_grafana == '1' && steps.prepare-alloy-log.outputs.file_exists == 'true'
+        uses: actions/upload-artifact@v4
+        with:
+          name: alloy-log-${{ runner.os }}-${{ matrix.python-version }}
+          path: /tmp/alloy-log-${{ runner.os }}-${{ matrix.python-version }}.tar.gz
         continue-on-error: true
 
       - name: Statistics
